### ISSUE TITLE
Feature request: Modify toArray method for custom keys

### ISSUE THREAD

**Issue by Philippe-Guyard** [kormanowsky/js-bit-list#1]
**Current behaviour**

    const numbers = [10, 20, 30];
    const NumbersBitList = BitList.useKeys(numbers);
    const numbersFromQuery = new NumbersBitList(1).toArray();
    //numberFromQuery is [1] (which means that numbers[0] is in the query)

**Expected behaviour**

    const numbers = [10, 20, 30];
    const NumbersBitList = BitList.useKeys(numbers);
    const numbersFromQuery = new NumbersBitList(1).toArray(); //you could name this .toNamedArray()
    //numberFromQuery is [10] (replacing true bit values by the actual keys)

**Comment by kormanowsky** [comment]
Added the feature in v2.2.0, use `.enabledKeys()`
